### ISSUE TITLE
run ` trex --custom React=https://dev.jspm.io/react/index.js` failed?

### ISSUE THREAD

**Issue by masx200** [crewdevio/Trex#143]
**Describe the bug** A clear and concise description of what the bug is.
run ` trex --custom React=https://dev.jspm.io/react/index.js` failed?
**To Reproduce** Steps to reproduce the behavior:
```
trex --custom React=https://dev.jspm.io/react/index.js

....   Installing React from dev.jspm.io
error: Uncaught (in promise) "\x1b[31mthis package is invalid or the url is invalid\x1b[39m"
```

**Expected behavior** A clear and concise description of what you expected to
happen.

**Screenshots** If applicable, add screenshots to help explain your problem.

**Desktop (please complete the following information):**

OS: Microsoft Windows [Version 10.0.22621.1702]
Deno version: deno 1.33.1 (release, x86_64-pc-windows-msvc)
Trex Version :trex: v1.12.1

**Additional context** Add any other context about the problem here.
```
curl https://dev.jspm.io/react/index.js
<!doctype html>
    <p>Not Found.</p>
```

react is  here 

https://ga.jspm.io/npm:react@18.2.0/dev.index.js

**Comment by RivierGrullon** [comment]
It is no longer a trex problem because the page https://dev.jspm.io/react/index.js is not being found, what you can do is the command trex --custom React=https://ga.jspm.io/npm:react@18.2.0/dev.index.js


what if we have to fix would be those strange characters that appear in the console: "\x1b[31mthis"
