### ISSUE TITLE
Install from jspm

### ISSUE THREAD

**Issue by jajaperson** [crewdevio/Trex#86]
**Is your feature request related to a problem? Please describe.**
It should be easier to install npm packages with Trex.

**Describe the solution you'd like**
A new install flag `--npm` (or something comparable) for installing from [`jspm.dev`](https://jspm.io)

**Describe alternatives you've considered**
Manual install with full URL or from a repository.

**Comment by jajaperson** [comment]
On second thoughts, [`skypack.dev`](https://skypack.dev) would probably be better.

**Comment by buttercubz** [comment]
Thank you very much for your suggestion, we currently have no plans to add additional specific flags to download from different registers as there are many and any server serving static js / ts files is a valid place to download those files. in any case the [`--custom`](https://github.com/crewdevio/Trex#adding-custom-packages) flag exists to fulfill those purposes since it can install from any valid place

**Comment by buttercubz** [comment]
We have two flags that allow us to install from deno.land and nest.land, in addition another one that allows us to install from a github repository, but just as we want to do it, there is no centralized place to register packages, the existence of those flags is that deno.land and nest.land are mostly focused on storing packages to be used with deno and for that reason we create those two flags but we do not want to lean towards one or some specific records and that is why there is the `--custom` flag

**Comment by jajaperson** [comment]
So to be clear you are not open to this feature at this point? Even if I implemented it?

**Comment by buttercubz** [comment]
> So to be clear you are not open to this feature at this point? Even if I implemented it? NPM still remains the largest registry for JS/TS modules, and skypack as far as I know is the best way to access it from within Deno.

you are right skypack and esm.sh are the ones who offer better compatibility with deno in npm packages, but adding more flags would be very verbose since if more records are created such as skypack or esm.sh it would also be necessary to create flags for it, `--custom` exists in order not to add more flags for different registers>

`example` from skypack

```console
trex --custom conffeti=https://cdn.skypack.dev/canvas-confetti?dts
```

`example` from esh.sh

```console
trex --custom react=https://esm.sh/react@17.0.1
```

**Comment by Okirshen** [comment]
A feature for adding custom flags would help that use case, for example

```
drex flags add sky https://www.skypack.dev/
```

then

```
drex i --sky canvas-confetti
```

**Comment by buttercubz** [comment]
for any case of external cdn the `--custom` command will meet the needs
